from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.home, name='home'),
    path('libros/', views.books_page, name='books_page'),
    path('libros/<int:book_id>/', views.book_detail, name='book_detail'),
    path('eventos/', views.events_page, name='events_page'),
    path('registro/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/configuracion/', views.update_club_settings, name='update_club_settings'),
    path('dashboard/reset-colores/', views.reset_colors, name='reset_colors'),
    path('libros/nuevo/', views.create_book, name='create_book'),
    path('libros/<int:book_id>/editar/', views.edit_book, name='edit_book'),
    path('libros/<int:book_id>/eliminar/', views.delete_book, name='delete_book'),
    path('libros/<int:book_id>/votar/', views.vote_book, name='vote_book'),
    path('libros/<int:book_id>/resena/', views.add_review, name='add_review'),
    path('eventos/nuevo/', views.create_event, name='create_event'),
    path('eventos/<int:event_id>/editar/', views.edit_event, name='edit_event'),
    path('eventos/<int:event_id>/eliminar/', views.delete_event, name='delete_event'),
    path('usuarios/pendientes/', views.pending_users, name='pending_users'),
    path('usuarios/<int:user_id>/aprobar/', views.approve_user, name='approve_user'),
    path('usuarios/<int:user_id>/editar/', views.edit_user, name='edit_user'),
    path('usuarios/<int:user_id>/eliminar/', views.delete_user, name='delete_user'),
    path('usuarios/<int:user_id>/suspender/', views.suspend_user, name='suspend_user'),
    path('usuarios/<int:user_id>/reactivar/', views.unsuspend_user, name='unsuspend_user'),
    path('usuarios/invitar/', views.invite_user, name='invite_user'),
    path('resenas/<int:review_id>/aprobar/', views.approve_review, name='approve_review'),
    path('resenas/<int:review_id>/marcar/', views.flag_review, name='flag_review'),
    path('resenas/<int:review_id>/eliminar/', views.delete_review, name='delete_review'),
    path('integraciones/redes/nueva/', views.add_social_link, name='add_social_link'),
    path('integraciones/redes/<int:link_id>/eliminar/', views.delete_social_link, name='delete_social_link'),
    path('integraciones/smtp/test/', views.test_smtp, name='test_smtp'),
    path('perfil/editar/', views.edit_profile, name='edit_profile'),
    path('pwa/manifest.json', views.manifest, name='manifest'),
    path('pwa/sw.js', views.service_worker, name='service_worker'),
]